package ua.kpi.tef.zu.controller;

public enum FieldID {
	FIRSTNAME, SECONDNAME, PATRONYM, LOGIN, COMMENT, GROUP, PHONE_LANDLINE, PHONE_MOBILE, PHONE_MOBILE2, EMAIL, SKYPE,
	ADDRESS_ZIP, ADDRESS_CITY, ADDRESS_STREET, ADDRESS_BUILDING, ADDRESS_APT
}
